name: Build and Deploy
on: # 只有在master分支发生push事件时 才会触发 workflow
  push:
    branches:
      - master
jobs: # 表示要执行的一项或多项任务
  build-and-deploy:
    runs-on: ubuntu-latest # 虚拟机构建环境使用 ubuntu
    steps: # 获取源码
      - name: Checkout
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false

      - name: Install and Build # 下载依赖 打包项目
        run: |
          npm install
          npm run build

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.7.1 # 使用别人写好的 actions 构建和部署
        with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 需要替换成你的
          BRANCH: master
          FOLDER: build
          # REPOSITORY_NAME: wangxiaochuan366/github-actions-demo # 这是我的 github page 仓库
          TARGET_FOLDER: github-actions-demo # 打包的文件将放到静态服务器 github-actions-demo 目录下
